import 'package:hive_flutter/hive_flutter.dart';
import '../models/user_config.dart';

// Register all Hive adapters
// This should be called once before using any Hive boxes
Future<void> registerAdapters() async {
  await Hive.initFlutter();
  
  // Register adapters (auto-generated by build_runner in user_config.g.dart)
  Hive.registerAdapter(UserConfigAdapter());
  Hive.registerAdapter(AppThemeAdapter());
}
