import 'package:hive_flutter/hive_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/user_config.dart';

class UserConfigManager {
  static final UserConfigManager _instance = UserConfigManager._internal();
  factory UserConfigManager() => _instance;
  UserConfigManager._internal();

  static const String _configBoxName = 'userConfig';
  static const String _apiKeyKey = 'apiKey';
  static const String _baseUrlKey = 'baseUrl';
  static const String _cacheEnabledKey = 'cacheEnabled';
  static const String _autoSaveEnabledKey = 'autoSaveEnabled';
  static const String _themeKey = 'theme';
  static const String _maxCacheSizeKey = 'maxCacheSize';

  late Box<UserConfig> _configBox;
  UserConfig? _cachedConfig;

  // MARK: - Initialize
  Future<void> initialize() async {
    await Hive.initFlutter();
    
    // Adapters are auto-generated by build_runner
    Hive.registerAdapter(UserConfigAdapter());
    Hive.registerAdapter(AppThemeAdapter());

    _configBox = await Hive.openBox<UserConfig>(_configBoxName);
  }

  // MARK: - Get Config
  UserConfig get config {
    if (_cachedConfig != null) {
      return _cachedConfig!;
    }

    final storedConfig = _configBox.get('config');
    if (storedConfig != null) {
      _cachedConfig = storedConfig;
      return storedConfig;
    }

    _cachedConfig = UserConfig.defaultConfig;
    return _cachedConfig!;
  }

  // MARK: - Save Config
  Future<void> saveConfig(UserConfig config) async {
    await _configBox.put('config', config);
    _cachedConfig = config;
  }

  // MARK: - Update API Key
  Future<void> updateAPIKey(String apiKey) async {
    final currentConfig = config;
    final updatedConfig = currentConfig.copyWith(apiKey: apiKey);
    await saveConfig(updatedConfig);
  }

  // MARK: - Update Base URL
  Future<void> updateBaseUrl(String baseUrl) async {
    final currentConfig = config;
    final updatedConfig = currentConfig.copyWith(baseUrl: baseUrl);
    await saveConfig(updatedConfig);
  }

  // MARK: - Update Theme
  Future<void> updateTheme(AppTheme theme) async {
    final currentConfig = config;
    final updatedConfig = currentConfig.copyWith(theme: theme);
    await saveConfig(updatedConfig);
  }

  // MARK: - Toggle Cache
  Future<void> toggleCache(bool enabled) async {
    final currentConfig = config;
    final updatedConfig = currentConfig.copyWith(cacheEnabled: enabled);
    await saveConfig(updatedConfig);
  }

  // MARK: - Toggle Auto Save
  Future<void> toggleAutoSave(bool enabled) async {
    final currentConfig = config;
    final updatedConfig = currentConfig.copyWith(autoSaveEnabled: enabled);
    await saveConfig(updatedConfig);
  }

  // MARK: - Validate API Key
  Future<bool> validateAPIKey(String apiKey) async {
    // TODO: Implement actual API key validation
    // For now, just check if it's not empty
    return apiKey.isNotEmpty;
  }

  // MARK: - Clear Config
  Future<void> clearConfig() async {
    await _configBox.clear();
    _cachedConfig = null;
  }

  // MARK: - Migration from SharedPreferences
  Future<void> migrateFromSharedPreferences() async {
    try {
      final prefs = await SharedPreferences.getInstance();

      final apiKey = prefs.getString(_apiKeyKey);
      final baseUrl = prefs.getString(_baseUrlKey);
      final cacheEnabled = prefs.getBool(_cacheEnabledKey);
      final autoSaveEnabled = prefs.getBool(_autoSaveEnabledKey);
      final theme = prefs.getString(_themeKey);
      final maxCacheSize = prefs.getInt(_maxCacheSizeKey);

      if (apiKey != null && apiKey.isNotEmpty) {
        await saveConfig(UserConfig(
          apiKey: apiKey,
          baseUrl: baseUrl ?? 'https://open.bigmodel.cn/api/paas/v4',
          cacheEnabled: cacheEnabled ?? true,
          autoSaveEnabled: autoSaveEnabled ?? true,
          theme: AppTheme.values.firstWhere(
            (t) => t.name == theme,
            orElse: () => AppTheme.system,
          ),
          maxCacheSize: maxCacheSize ?? 100,
        ));

        // Clear old preferences
        await prefs.clear();
      }
    } catch (e) {
      // Migration failed, but that's okay
      print('Migration failed: $e');
    }
  }
}
